apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  namespace: sample-grafana
  labels:
    app: sample-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
        - name: web
          image: us-central1-docker.pkg.dev/internal-sandbox-446612/velero-artifact/sample-python-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "128Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "256Mi"
          volumeMounts:
            - name: app-storage
              mountPath: /data
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: sample-app-pvc
